---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: admin
    name: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    author: admin
    name: redis-pod
...