---
apiVersion: v1
kind: Service
metadata:
  name: results-app-service
  labels:
    author: admin
    name: results-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetport: 80
      nodeport: 30008
  selector:
    author: admin
    name: results-app-pod
...