---
apiVersion: v1
kind: Pod
metadata:
  name: results-app-pod
  labels:
    author: admin
    name: results-app-pod
spec:
  containers:
    - name: results-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
...
