---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: admin
    name: voting-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targePort: 80
      nodePort: 30008

  selector:
    author: admin
    name: voting-app-pod
...